### PR TITLE
Allow a CACHE_PREFIX for location ID's

### PR DESCRIPTION
**Pull request by scottconnerly**

### CODE REVIEW

**Review by pcarn — CHANGES_REQUESTED** [review]
Can we change these to `os.environ.get("CACHE_PREFIX", "")` so it won't error if the env var isn't set?

**Comment by pcarn** [comment]
[precommit lint](https://github.com/pcarn/vaccine-watch#lint) fails, I can commit to your fork if you don't want to install it

**Comment by AnEmortalKid** [comment]
Mind adding a note on the readme for this? I’m not familiar with what this would do, my guess is you’d set a prefix in case you were running multiple instances against the same redis server?

**Review by pcarn — APPROVED** [review]

**Comment by pcarn** [comment]
@scottconnerly After merging I realized we need this on the tweet redis also. 
I added it here: https://github.com/pcarn/vaccine-watch/commit/5ffa508302a167025b54dd069dc645df5e24a817

**Pull request merged**
